name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and create a file
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HPC_SSH_HOST }}
        username: s2316443
        key: ${{ secrets.HPC_SSH_PRIVATE_KEY }}
        passphrase: q980330
        script: touch test.txt
        password: huangzihe980330
